#!/usr/bin/env sh

dir=$(cd $(dirname "$0") && pwd)
source "$dir/variables.sh"

config_container="$GCLOUD_PROJECT""-gcloud-config"
fleet_image="$GCLOUD_PROJECT""-fleet"

if [ -z "`docker ps -a | grep $config_container`" ] ; then
	echo "It seems you have not yet authenticated with google cloud"
	echo "Please run ./gcloud reauth, and follow instructions to create credentials"
	exit 1
fi

if [ -z "`docker images | grep $fleet_image`" ] ; then
	echo "You have not build the fleet image for this project yet"
	echo "Please do so (see the Makefile in this directory"
	exit 1
fi

docker run -it --volumes-from $config_container \
	-e FLEETCTL_TUNNEL=`cat $dir/.entry-node` \
	-e FLEET_VERIFY_UNITS=true \
	-e FLEETCTL="/root/fleet/bin/fleetctl" \
	-e ENTRY_NODE=`cat $dir/.entry-node` \
	-w / \
	--entrypoint /ssh_and_do \
	-v $(pwd)/services:/services \
	-v $dir/scripts/ssh_and_do:/ssh_and_do \
	$fleet_image $@

