#!/usr/bin/env bash

dir=$(cd $(dirname "$0") && pwd)

export GCLOUD_PROJECT=`cat $dir/../.project`
export GCLOUD_ZONE=`cat $dir/../.zone`

config_container="$GCLOUD_PROJECT""-gcloud-config"

if [[ "$1" = "reauth" ]] ; then
	docker rm -f $config_container
fi

# If we do not have a config container, then we need to auth
if [[ ! `docker ps -a | grep $config_container` ]] ; then

	echo -e "\e[1;33m"

	echo "No config parameters found. Doing now"
	docker run -t -i --name $config_container -v /.ssh -v /.config \
        -e GCLOUD_PROJECT=$GCLOUD_PROJECT -e GCLOUD_ZONE=$GCLOUD_ZONE \
	-v $dir/scripts:/scripts -v $dir:/files \
	google/cloud-sdk /scripts/gcloud-helper auth

	echo -e "\e[0m"
else
	docker run --rm -it --volumes-from $config_container \
		-v $dir/cloud-config.yaml:/cloud-config.yaml \
		-v $dir/scripts:/scripts -v $dir:/files \
		google/cloud-sdk gcloud $@
fi
