#!/usr/bin/env bash

local_file="$1"
dir=$(cd $(dirname "$0") && pwd)
config_container="$GCLOUD_PROJECT""-gcloud-config"

source $dir/variables.sh

$dir/gcloud compute copy-files --zone $GCLOUD_ZONE /files/$local_file ${@:2}
